# curl localhost:8888/bar/foo/ -H "X-Config-Token: vault-plaintext-root-token"
GET localhost:8888/bar/foo/
X-Config-Token: vault-plaintext-root-token

###

# curl localhost:8888/bar-foo.properties -H "X-Config-Token: vault-plaintext-root-token"
GET localhost:8888/bar-foo.properties
X-Config-Token: vault-plaintext-root-token

###

# curl localhost:7654/refreshed
GET localhost:7654/refreshed

###

# curl localhost:7654/configprop
GET localhost:7654/configprop

###

# curl localhost:7654/encrypted
GET localhost:7654/encrypted


###

