# curl localhost:8888/encrypt -d "my secret"
POST localhost:8888/encrypt
Content-Type: application/x-www-form-urlencoded

my secret

###

# curl localhost:8888/decrypt -d "3b0b19f0dfeb65f16c25733557448eae53e30e9b2bdafcff191617683ac674b5"
POST localhost:8888/decrypt
Content-Type: application/x-www-form-urlencoded

3b0b19f0dfeb65f16c25733557448eae53e30e9b2bdafcff191617683ac674b5
