version: "3.8"
services:
  consul:
    image: progrium/consul
    extra_hosts: ['host.docker.internal:host-gateway']
    command: -server -bootstrap
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
