{
 "title": "Frauds",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Frauds Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frauds_current" }
   ]
  },
  {
   "title": "Frauds Time Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frauds_time_seconds_count" }
   ]
  },
  {
   "title": "Frauds Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "frauds_counter_total" }
   ]
  }
 ]
}