# curl -v localhost:6543/httpbin/headers --cookie 'spring=cloud'
POST localhost:6543/httpbin/headers
Cookie: spring=cloud

asd

###

# curl localhost:6543/check/account -H 'X-Operation-Type: Fraud'
GET localhost:6543/check/account
X-Operation-Type: Fraud

###

