version: '3.8'
services:
  consul:
    image: progrium/consul
    extra_hosts: ['host.docker.internal:host-gateway']
    command: -server -bootstrap
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600

  rabbitmq:
    image: rabbitmq:management
    extra_hosts: ['host.docker.internal:host-gateway']
    ports:
      - 5672:5672
      - 15672:15672

  # https://developer.confluent.io/quickstart/kafka-docker/
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    extra_hosts: ['host.docker.internal:host-gateway']
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    extra_hosts: ['host.docker.internal:host-gateway']
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
